name: Despliegue sitio
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Revisando codigo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Instalando dependencias
        run: npm install

      - name: Construyendo sitio
        run: npm run build

      - name: lista archivos
        run: ls

      # Aquí debes agregar los pasos para desplegar el sitio, como empujar los archivos generados a GitHub Pages
