name: Despliegue sitio
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps: 
      - name: Revisando codigo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Instalando dependencias
        run: npm install

      - name: Construyendo sitio
        run: npm run build

      - name: lista archivos
        run: ls
      - name: Entrar a dist
        run: |
          cd ./dist
          ls
      - name: subir sitio
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Actualizacion sitio web
            branch: deploy
            file_pattern: './dist/*'
            commit_user_name: Julián Araya [GitHub Actions]
            commit_user_email: jul.dev03@gmail.com
            commit_author: Jul879n
            create_branch: true
