name: Build and Deploy
on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["deploy"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git user
              run: |
                  git config --global user.email jul.dev03@gmail.com
                  git config --global user.name "Julián Araya"
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"
            - name: Ver archivos
              run: ls
            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build
            - name: Ver archivos build
              run: ls
            - name: Copy files to Deploy branch
              run: |
                  git branch
                  git checkout deploy
                  git add dist/*
                  git commit -m "Agregando cambios para la funcionalidad X"
                  git push origin deploy
